flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- http-client-0.5.11
- http-client-tls-0.3.5.3
- QuickCheck-2.9.2
- aeson-1.3.1.0
- pretty-simple-2.1.0.0

- attoparsec-0.13.2.2
- base-compat-0.10.1
- blaze-builder-0.4.1.0
- case-insensitive-1.2.0.11
- connection-0.2.8
- cookie-0.4.4
- cryptonite-0.25
- data-default-class-0.1.2.0
- dlist-0.8.0.4
- exceptions-0.10.0
- hashable-1.2.7.0
- http-types-0.12.1
- memory-0.14.16
- mime-types-0.1.0.7
- mtl-2.2.2
- network-2.7.0.0
- network-uri-2.6.1.0
- random-1.1
- scientific-0.3.6.2
- stm-2.4.5.0
- streaming-commons-0.2.0.0
- tagged-0.8.5
- text-1.2.3.0
- tf-random-0.5
- th-abstraction-0.2.6.0
- time-locale-compat-0.1.1.4
- tls-1.4.1
- unordered-containers-0.2.9.0
- uuid-types-1.0.3
- vector-0.12.0.1

- asn1-encoding-0.9.5
- asn1-types-0.3.2
- async-2.2.1
- basement-0.0.7
- byteable-0.1.1
- cereal-0.5.5.0
- foundation-0.0.20
- integer-logarithms-1.0.2.1
- old-locale-1.0.0.7
- parsec-3.1.13.0
- primitive-0.6.3.0
- socks-0.5.6
- transformers-compat-0.6.1.6
- x509-1.7.3
- x509-store-1.6.6
- x509-system-1.6.6
- x509-validation-1.6.10
- zlib-0.6.2

- asn1-parse-0.9.4
- hourglass-0.2.11
- pem-0.2.4
- ansi-terminal-0.8.0.4
- colour-2.3.4

allow-newer: true

resolver: ghc-8.0.2
