module Text.HTML.ValueCalc.Lists.OMXList

(omxList) where

omxList :: [String]
omxList = ["aarhuskarlshamn","abb-ltd","acando-b","acap-invest-a","acap-invest-b","active-biotech",
           "addnode-b","addtech","aerocrine-ab","af-ab","alfa-laval","allenex-b","alltele-allmanna-svenska-telefon",
           "anoto-group","arcam-ab","arctic-paper","arise-windpower","aspiro-ab","assa-abloy","astrazeneca",
           "atlas-copco-a","atlas-copco-b","atrium-ljungberg","autoliv-inc","phonera","avanza-bank-holding",
           "avega-group","axfood-ab","axis","b-b-tools","be-group","g-l-beijer","beijer-alma","beijer-electronics",
           "bergs-timber-b","betsson-b","bilia-a","billerud","biogaia","bioinvent","biotage","bjorn-borg","bef-sdb",
           "blackpearl-resources-inc","boliden","bong-ab","boul-ab","bts-group-b","bure-equity","byggmax-group",
           "castellum-ab","catena","cavotec-sa","cdon-group","cellavision","cision-ab","clas-ohlson-b","cloetta",
           "concentric","concordia-b","connecta","consilium-b","corem-property","ctt-systems-ab","cybercom-group-ab",
           "dedicare","dgc-one-ab","dios-fastigheter","doro","duni","duroc-b","east-capital-explorer","elanders-ab-b",
           "electra-gruppen","electrolux","electrolux-b","elekta","elos-b","endomines-publ-ab","enea","eniro","enquest",
           "epicept","telefon-lm-ericsson","ericsson-b","etrion-corporation","ework-scandinavia-ab","fabege","fagerhult",
           "fast-partner","fastighets-ab-balder","feelgood-svenska","fenix-outdoor-ab","fingerprint-cards","finnvedenbulten",
           "formpipe-software-ab","getinge","geveko-b","global-health-partner","gunnebo","hakon-invest","haldex",
           "heba-fastighets-ab","hemtex","hennes---mauritz","hexagon","hexpol-b","hiq-international","hms-network",
           "holmen-a","holmen","hufvudstaden","hufvudstaden-ab","husqvarna-a","husqvarna-b","iar-systems-group-b",
           "image-systems","ind.---financial-systems-ifs-a","ind.---financial-systems-ifs-b","industrivarden",
           "industrivarden-ab","indutrade","intellecta","intrum-justitia","investor-a","investor","itab-shop-concept",
           "jm-ab","kabe-husvagnar-b","kappahl","karo-bio","karol-devel-b","kinnevik-investment-a","kinnevik-investment-b",
           "klovern","know-it","kungsleden-ab","lagercrantz-group","lammhults-design-group","latour-investment",
           "lindab-international","loomis-ab","lundbergforetagen","lundin-mining","lundin-petroleum","malmbergs-elektriska",
           "meda-ab","medivir","mekonomen","melker-schorling","micro-systemation-ab","micronic-mydata","midsona-a","midsona-b",
           "midway-holding-a","midway-holding-b","millicom-international-cellular","moberg-derma-ab","modern-times-a",
           "modern-times-b","mq-holding-ab","msc-konsult-b","multiq-intl","ncc-a","ncc-b","nederman-holding","net-entertainment-ne-ab",
           "net-insight-b","neurovvive-pharmaceutical-ab","new-wave-group-ab","nibe-industrier-b","nobia","nokia-finland","nolato-b",
           "nordea-bank-(st)","nordic-mines","nordic-service-partners-holding","nordnet","note","novestra","novotek-b","oasmia",
           "odd-molly-int","oem-international","opcon","investment-ab-oresund","orexo","oriflame-cosmetics","ortivus-a","ortivus-b",
           "pa-resources","partnertech","peab-ab","pfizer","poolia-b","precise-biometrics-ab","prevas-b","pricer-b","proact-it-group",
           "probi","proffice-b","profilgruppen-b","ratos-a","ratos-ab","raysearch-laboratories","readsoft-b","rederi-transatlantic-ab",
           "rejlerkoncernen-b","rezidor-hotel-gr","rnb-retail---brands","rorvik-timber-b","rottneros","saab-ab","sagax","sagax-ab",
           "sandvik","sas-ab","scania-ab","scania-b","seamless-distribution-ab","sectra-ab","securitas-b","semafo","semcon","sensys-traffic",
           "shelton-petroleum-ab","sintercast","s.e.b","skandinaviska-enskilda-banken","skanska-b","skf","skf-b","skistar-ab","softronic-ab",
           "ssab","ssab-ab","stjarnafyrkant","stora-enso-a","stora-enso-exch","studsvik","svedbergs-i-dalstorp","svenska-cellulosa",
           "svenska-cell","svenska-handelsbanken","svenska-handelsbanken-ab","sweco-a","sweco-b","swedbank","swedish-match",
           "swedish-orphan-biovitrum","swedol-ab","systemair","tele2-a","tele2","teliasonera","tethys-oil-ab","tietoenator","traction-b",
           "tradedoubler","transcom-worldwide-a","transcom-worldwide-b","transmode-holding-ab","trelleborg","trigon-agri","unibet-group-plc",
           "uniflex-b","vbg-group-ab","venue-retail","vitec-b","vitrolife","volvo-a","volvo-b","vostok-nafta-investment","wallenstam",
           "wihlborgs-fastigheter","xano-industri-b"]
